; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = native

extra_configs =
	common_settings.ini
  	variants/*/platformio.ini

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

[env:esp32]
extends = env
platform = espressif32 @ 6.7.0
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
board_build.embed_files = 
	data_embed/index.html.gz
	data_embed/style.css.gz
	data_embed/script.js.gz
	data_embed/bootstrap.css.gz
	data_embed/bootstrap.js.gz
	data_embed/favicon.png.gz
extra_scripts = 
	pre:tools/compress.py
	debug_tool = esp-prog

[env:native]
platform = native
framework =
test_framework = googletest
lib_deps =
lib_ignore = NeoGPS
build_flags =
    -D UNIT_TEST
    -I test/
    -I include/
    -std=c++17

[env:test_map_gps]
platform = native
framework =
test_framework = googletest
lib_ignore = NeoGPS
build_flags =
    -D UNIT_TEST
    -I test/
    -I include/
    -std=c++17
# On inclut que le filtre GPS et on exclut tout le code source ESP32
test_build_src = yes
build_src_filter = +<../lib/MapGPSFilter/> -<../src/>

[env:test_integration]
platform = native
framework =
test_framework = googletest
lib_ignore = NeoGPS
build_flags =
    -D UNIT_TEST
    -I test/
    -I include/
    -std=c++17
test_build_src = yes
build_src_filter = +<../lib/MapGPSFilter/> -<../src/>
