; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = gat562_mesh_trial_tracker

extra_configs =
	common_settings.ini
	variants/*/platformio.ini

[env]
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

[env:gat562_mesh_trial_tracker]
extends = nrf52840_base
board_level = extra
board = nrf52840_dk
board_check = false
# 使用自定义引脚配置
build_flags = ${nrf52840_base.build_flags}
  -I variants/gat562_mesh_trial_tracker
  -D GAT562_MESH_TRIAL_TRACKER
  -D PRIVATE_HW
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter} +<variants/gat562_mesh_trial_tracker> -<bluetooth_utils.cpp> -<wifi_utils.cpp> -<web_utils.cpp> -<winlink_utils.cpp> -<wx_utils.cpp> -<station_utils.cpp> -<msg_utils.cpp>
lib_deps =
  ${nrf52840_base.lib_deps}

[nrf52_base]
platform = nordicnrf52
framework = arduino
build_flags = 
	-Wall
	-Wno-error
	-DNO_WIFI_SUPPORT
	-D__cplusplus=201103L
	-DNOMINMAX
	-D_GLIBCXX_USE_NANOSLEEP=1
	-fno-exceptions
	-fno-rtti
	-DRADIOLIB_EXCLUDE_CC1101=1
	-DRADIOLIB_EXCLUDE_NRF24=1
	-DRADIOLIB_EXCLUDE_RF69=1
	-DRADIOLIB_EXCLUDE_SX1231=1
	-DRADIOLIB_EXCLUDE_SX1233=1
	-DRADIOLIB_EXCLUDE_SI443X=1
	-DRADIOLIB_EXCLUDE_RFM2X=1
	-DRADIOLIB_EXCLUDE_AFSK=1
	-DRADIOLIB_EXCLUDE_BELL=1
	-DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
	-DRADIOLIB_EXCLUDE_MORSE=1
	-DRADIOLIB_EXCLUDE_RTTY=1
	-DRADIOLIB_EXCLUDE_SSTV=1
	-DRADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
	-DRADIOLIB_EXCLUDE_BELL=1
	-DRADIOLIB_EXCLUDE_PAGER=1
	-DRADIOLIB_EXCLUDE_FSK4=1
	-DRADIOLIB_EXCLUDE_LORAWAN=1
	-DNRF52840_PLATFORM
	-DNO_SPIFFS_SUPPORT
	-D__STDC_LIMIT_MACROS
	-D__STDC_CONSTANT_MACROS
build_src_filter = +<*> -<.git/> -<.svn/>
lib_deps =
	adafruit/Adafruit BusIO @ 1.16.1
	adafruit/Adafruit Unified Sensor @ 1.1.14
	bblanchon/ArduinoJson @ 6.21.3
	jgromes/RadioLib @ 7.1.0
	mikalhart/TinyGPSPlus @ 1.0.3
	paulstoffregen/Time @ 1.6.1
	# peterus/esp-logger @ 1.0.0 - 移除，因为它依赖WiFiUdp.h
	h2zero/NimBLE-Arduino @ 1.4.1
	richonguzman/APRSPacketLib @ 1.0.0
	shaggydog/OneButton @ 1.5.0

; 测试环境，只编译测试文件，用于解决min/max宏冲突问题
[env:nrf52_test_min_max]
platform = nordicnrf52
framework = arduino
board = adafruit_feather_nrf52840
build_flags = 
     -Wall
     -DNO_WIFI_SUPPORT
     -D__cplusplus=201103L
     -DNOMINMAX
     -D_GLIBCXX_USE_NANOSLEEP=1
     -fno-exceptions
     -fno-rtti
     -Umin
     -Umax
    -D__STDC_LIMIT_MACROS
    -D__STDC_CONSTANT_MACROS
    -DNRF52840_PLATFORM
    -DNO_SPIFFS_SUPPORT

build_src_filter = 
     +<main.cpp>
     -<*> ; 排除所有其他源文件

lib_deps =

[nrf52840_base]
extends = nrf52_base
platform = nordicnrf52
framework = arduino
build_flags = 
	${nrf52_base.build_flags}
	-DARDUINO_NRF52840_DK
board_build.mcu = nrf52840
board_build.f_cpu = 64000000L
lib_deps =
	${nrf52_base.lib_deps}
	adafruit/Adafruit GFX Library @ 1.11.9
	adafruit/Adafruit SSD1306 @ 2.5.10
	adafruit/Adafruit SH110X @ 2.1.10

[env:esp32]
extends = env
platform = espressif32 @ 6.7.0
board = esp32dev
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
board_build.embed_files = 
	data_embed/index.html.gz
	data_embed/style.css.gz
	data_embed/script.js.gz
	data_embed/bootstrap.css.gz
	data_embed/bootstrap.js.gz
	data_embed/favicon.png.gz
extra_scripts = 
	pre:tools/compress.py
debug_tool = esp-prog